---
- hosts: all
  user: root
  become: true
 
  vars:
    pack_name: httpd
    serv_name: httpd

  tasks:
    - name: Install {{ pack_name }}
      yum: pkg={{ pack_name }} state=installed
    - name: Starte {{ serv_name }}
      service: name={{ serv_name }} state=started

